#!/bin/bash

#
# Add this to /etc/profile
# example:
#    /usr/local/bin/dynmotd
# Don't forget to chmod +x it.
# Create /etc/motd-maint to track changes that need to be posted
#


EMAIL="jjasghar@gmail.com"
PROCCOUNT=`ps -Afl | wc -l`
PROCCOUNT=`expr $PROCCOUNT - 5`
NIC=eth0
IPADDY=`ifconfig $NIC | grep inet | awk -F " " '{print $2}' | grep -v :: | sed 's/addr://g'`
DATE=`date +%F`
EPOCH=`date +%s`
UPTIME=`uptime` # | sed 's/.*up ([^,]*), .*/1/'`

echo -e "
#################################################################################
WARNING:- YOU MUST HAVE PRIOR AUTHORIZATION TO ACCESS THIS SYSTEM. ALL 
CONNECTIONS ARE LOGGED AND MONITORED. BY CONNECTING TO THIS SYSTEM YOU FULLY
CONSENT TO ALL MONITORING. UN-AUTHORIZED ACCESS OR USE WILL BE PROSECUTED TO
THE FULL EXTENT OF LAW. YOU HAVE BEEN WARNED
#################################################################################
"

echo -e "
+++++++++++++++++++++++++++++++++: System Data :++++++++++++++++++++++++++++++++++
+ hostname = `hostname`
+ address  = $IPADDY
+ os type  = `uname -s`
+ kernel   = `uname -r`
+ uptime   = $UPTIME
++++++++++++++++++++++++++++++++: User Data :+++++++++++++++++++++++++++++++++++++
+ username  = `whoami`
+ processes = $PROCCOUNT of `ulimit -u` 
+++++++++++++++++++++++++++: Helpful Information :++++++++++++++++++++++++++++++++
+ admin = $EMAIL
+ date  = $DATE
+ epoch = $EPOCH
+++++++++++++++++++++++++: Maintenance Information :++++++++++++++++++++++++++++++
+ `cat /etc/motd-maint`
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
"
