
delete from EUD_ITEM where START_DATE < (sysdate - 400) and IMPORTANT_IND = 'N';
commit;
delete from EUD_ITEM where START_DATE < (sysdate - 350) and IMPORTANT_IND = 'N';
commit;
delete from EUD_ITEM where START_DATE < (sysdate - 300) and IMPORTANT_IND = 'N';
commit;
delete from EUD_ITEM where START_DATE < (sysdate - 290) and IMPORTANT_IND = 'N';
commit;
delete from EUD_ITEM where START_DATE < (sysdate - 280) and IMPORTANT_IND = 'N';
commit;
delete from EUD_ITEM where START_DATE < (sysdate - 270) and IMPORTANT_IND = 'N';
commit;
delete from EUD_ITEM where START_DATE < (sysdate - 260) and IMPORTANT_IND = 'N';
commit;
delete from EUD_ITEM where START_DATE < (sysdate - 250) and IMPORTANT_IND = 'N';
commit;
delete from EUD_ITEM where START_DATE < (sysdate - 240) and IMPORTANT_IND = 'N';
commit;
delete from EUD_ITEM where START_DATE < (sysdate - 230) and IMPORTANT_IND = 'N';
commit;
delete from EUD_ITEM where START_DATE < (sysdate - 220) and IMPORTANT_IND = 'N';
commit;
delete from EUD_ITEM where START_DATE < (sysdate - 210) and IMPORTANT_IND = 'N';
commit;
delete from EUD_ITEM where START_DATE < (sysdate - 200) and IMPORTANT_IND = 'N';
commit;
delete from EUD_ITEM where START_DATE < (sysdate - 190) and IMPORTANT_IND = 'N';
commit;
delete from EUD_ITEM where START_DATE < (sysdate - 180) and IMPORTANT_IND = 'N';
commit;
