#!/bin/bash
tmux has-session -t development 
if [ $? != 0 ]
  then
    tmux new-session -s development -n editor -d
    tmux send-keys -t development 'cd ~/repo' C-m
    tmux send-keys -t development 'vim' C-m
    tmux split-window -v -t development
    tmux split-window -v -p 10 -t development
    tmux select-layout -t development main-horizontal

    tmux new-window -n console -t development
    tmux send-keys -t development:2 'cd ~/repo' C-m
  fi
tmux attach -t development
